name: Schedule the Reddit Post

# posts once a day at 10am a reddit post to the subreddit r/dhgememes
# the post is about the meals from the mensa in the DHGE (Gera)

on:
  workflow_dispatch: # possible to run from ui, when needed
  schedule:
    # once a day at 10am (except on weekend)
    # cron uses UTC-timezone -> germany (berlin) is in the timezone UTC+1
    - cron: '0 9 * * 1-5'

permissions:
  contents: read
  issues: write

jobs:
  schedule_reddit_post:
    name: Schedule Reddit Post
    runs-on: ubuntu-latest
    steps:
      - name: Check out repositories default branch
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install PRAW
        run: pip install praw
      - name: Run script
        run: python reddit_bot.py